### ISSUE TITLE
Release 1.0, pre-release tasks

### ISSUE THREAD

**Issue by dansondergaard** [gwforg/gwf#110]
- [x] Make sure that all of the documentation is up to date
- [x] Document how to contribute, model after [this](https://home-assistant.io/developers/development_submitting/)
- [x] Document release process
- [x] Either vendor in statusbar package or add it to gwforg repository
- [x] Remove beta development status classifier from setup.py

**Comment by dansondergaard** [comment]
Or should we point the old documentation to the new one? @mailund?

**Comment by mailund** [comment]
I think we should keep the pages but update them. It is a good place to have a "getting started" tutorial

**Comment by dansondergaard** [comment]
Doesn't it make more sense to keep all documentation in one location? There's already "Tutorial" and "Getting Started" sections in the docs on ReadTheDocs.

**Comment by andreasnoack** [comment]
It would be great to either remove http://mailund.github.io/gwf//documentation/ or write clearly in the top that it is outdated. I've just spent an hour or so trying to figure out why nothing worked because I was reading the old documentation.

**Comment by dansondergaard** [comment]
@andreasnoack The plan is definitely to remove the old documentation, but we can't really do so before gwf 1.0 is released, which won't be right now since I'm pretty busy. That's also why the examples haven't been updated yet.

**Comment by andreasnoack** [comment]
That makes sense. It would be helpful, though, with a comment in the top of the old documentation. I'm also a little confused about the release because I installed from Anaconda, https://anaconda.org/dansondergaard/gwf, and that seems to be a version that matches the new documentation.

**Comment by dansondergaard** [comment]
@andreasnoack I agree - I'll try to get @mailund to add a comment about it. You're correct that the conda package is 1.0.0, but that's just me fooling around with how to create conda packages :) Sorry about the confusion! However, it's great to hear that you were able to install gwf with conda!

**Comment by mailund** [comment]
I have deleted the gh-pages branch, so the old documentation shouldn't be online any longer.

**Comment by dansondergaard** [comment]
@mailund Could you please move the repo to `gwforg`? :)

**Comment by mailund** [comment]
I have moved it.
