### ISSUE TITLE
Config command

### ISSUE THREAD

**Issue by dansondergaard** [gwforg/gwf#148]
Right now there's no configuration at all (I removed it because it sucked). This also means that it's not possible to configure e.g. which port the local backend should expect the workers to be on, because the backends have no way of being configured. The easy solution:

1. at initialization, read a JSON file with configuration from the working dir (this requires the workflow to be loaded)
2. override config values with parameters given on the command line.
3. store configuration in the context

Backends can be given the config when initialized. Commands/plugins can access it via a `pass_config` decorator.

**Comment by mailund** [comment]
I don't know if it is related to this, but there *is* a config command---the help for it says "See `gwf config --help`", but doing that raises an exception

```
$ gwf config --help                            [Py35] 🐍
Usage: gwf config [OPTIONS]

  Warning: entry point could not be loaded. Contact its author for help.

  Traceback (most recent call last):
    File "/Users/mailund/anaconda/envs/Py35/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2266, in resolve
      return functools.reduce(getattr, self.attrs, module)
  AttributeError: module 'gwf.plugins.config' has no attribute 'config'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):   File
  "/Users/mailund/anaconda/envs/Py35/lib/python3.5/site-
  packages/click_plugins/core.py", line 37, in decorator
  group.add_command(entry_point.load())   File
  "/Users/mailund/anaconda/envs/Py35/lib/python3.5/site-
  packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line
  2258, in load     return self.resolve()   File
  "/Users/mailund/anaconda/envs/Py35/lib/python3.5/site-
  packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line
  2268, in resolve     raise ImportError(str(exc)) ImportError: module
  'gwf.plugins.config' has no attribute 'config'

Options:
  --help  Show this message and exit.
```

**Comment by dansondergaard** [comment]
Yeah, that's because there's no config command, only a registered entrypoint (that doesn't lead to anything) ;)
