### ISSUE TITLE
Editor support

### ISSUE THREAD

**Issue by dansondergaard** [gwforg/gwf#154]
Would be really cool to have some editor support for *gwf*. I wrote two snippets for Visual Studio Code:

```json
{
    "GWF target": {
        "prefix": "targ",
        "body": [
            "gwf.target('$1', inputs=[$2], outputs=[$3]) << \"\"\"",
            "$4",
            "\"\"\"",
            "",
            "$0"
        ],
		"description": "GWF target"
    },
	"GWF target from template": {
        "prefix": "tmpl",
        "body": [
            "gwf.target('$1', inputs=[$2], outputs=[$3]) << $4($5)",
            "",
            "$0"
        ],
		"description": "GWF target from template"
    }
}
```

Demonstration:

![vsc-gwf-snippets](https://cloud.githubusercontent.com/assets/204911/25837187/ca6e1b96-34cf-11e7-96fe-e53c459b887d.gif)

Should be easy to add similar stuff for Sublime Text, Emacs (?) and Atom. Not sure whether we should make installable packages for each editor or just add the code to a directory called `editor-support` in the repo, with a small description of how to set them up.

**Comment by mailund** [comment]
I think this is a fabulous idea. I don't have any strong preferences as to how we install plugins, but we probably do not want to do it silently when `gwf` is installed.

We have the organisation now; would this be something we should put in a separate repository? Perhaps a repository per editor we support?

**Comment by dansondergaard** [comment]
I wan't to keep it simple to begin with (since we only have two snippets for VS Code, there's no reason to waste time making packages etc.), so my idea was to have a `editor-support` dir in the repository with subdirs for each editor.

As the integrations expand and improve, we can then consider having individual repos and make them actual, installable packages (at least both Atom, Sublime and VS Code have their own package managers).

**Comment by dansondergaard** [comment]
@micknudsen said he'd make similar snippets for Atom, I think that's a good start. Snippets for Sublime Text would probably be good too.

**Comment by dansondergaard** [comment]
I will keep this issue open without a milestone, so that it's the place to discuss editor support.
