### ISSUE TITLE
Improvements to local backend

### ISSUE THREAD

**Issue by dansondergaard** [gwforg/gwf#169]
**Note: This should go in 1.5 or 2.0, I want a stable, well-tested base first. Just putting some thoughts out in the open...**

The local backend is really nice to have and allows for quick testing of workflows, as well as running small workflows locally. @micknudsen also uses it for automatic testing of workflows on TravisCI.

However, the local backend currently has a few problems:

1. Functionality
    1. No support for cancelling a task.
    2. No access to resource usage of a task.
    3. We do not support tasks using more than one core, limiting memory usage etc.
2. Correctness
    1. Doubtful whether data synchronization between processes is performed correct.
    2. Very difficult to write unit tests for.

Problem 1i can be solved by not running the task directly in the worker process. Currently, the worker process blocks while running the task, making it impossible to tell the worker to cancel the task.

Problem 1ii is hard to solve in a cross-platform fashion, however, maybe [1] can help with that.

Problem 1iii depends on 1ii and is not as necessary as other things in this issue. It's a nice-to-have though.

Problem 2i I'm not sure how to solve yet. Ideally, I'd like all messaging to happen with queues and all logic regarding waiting for dependencies to complete, keeping track of status and re-queueing tasks to be carried out by a "master" process, so that synchronization between processes is limited to (1) enqueuing a task and (2) communication status/resource information back to the master. Both can happen through queues.

Problem 2ii I'm not sure about either, but it should be easier when the dependency-handling logic is isolated outside the worker code.

[1] https://github.com/giampaolo/psutil

**Comment by micknudsen** [comment]
I actually only *thought* about automatic testing of workflows on TravisCI, and I have since given up on that. I never use the local backend for anything.

**Comment by dansondergaard** [comment]
@micknudsen Why could you not get it to work on Travis? What were you trying to do?

**Comment by micknudsen** [comment]
I have absolutely no recollection of what I tried to do. Anyway, I don't think testing workflows using Travis is the way to go. You basically end up testing third-party software.

**Comment by dansondergaard** [comment]
I agree. The local backend was also mostly meant for testing without access to a real cluster.

**Comment by dansondergaard** [comment]
#275 has addresses some of these issues (correctness and cancellation). Resource tracking is coming up too.
