### ISSUE TITLE
Exception when targets in different namespaces produce the same file

### ISSUE THREAD

**Issue by dansondergaard** [gwforg/gwf#176]
This example:

```python
w1 = Workflow(name='foo')
w1.target('SayHello', inputs=[], outputs=['greeting.txt'])

w2 = Workflow(name='bar')
w2.target('SayHi', inputs=[], outputs=['greeting.txt'])
w2.include(w1)

g = Graph(targets=w2.targets)
```

raises a `FileProvidedByMultipleTargetsError`, which is quite sensible. It's non-problematic in the case where the working directories are different:

```python
w1 = Workflow(name='foo', working_dir='/some/dir')
w1.target('SayHello', inputs=[], outputs=['greeting.txt'])

w2 = Workflow(name='bar', working_dir='/some/other/dir')
w2.target('SayHi', inputs=[], outputs=['greeting.txt'])
w2.include(w1)

g = Graph(targets=w2.targets)
```

Which *gwf* accepts without error. I'm not sure what the semantics should be with this. I never used `Workflow.include` myself, so I'm not sure about the use cases.

Should we raise an error if including a workflow with the same working dir as the includer? @mailund?

**Comment by mailund** [comment]
As long as the files actually produced are different, i do not consider it an error. If targets produce the same file, it is.
