### ISSUE TITLE
Re-run target if target spec has changed

### ISSUE THREAD

**Issue by dansondergaard** [gwforg/gwf#180]
Right now we only look at timestamps and file existence to determine whether a target should run.

Often a target should also run if the target spec has changed. We could hash the specs and save the hashes to a file on each run. A target should run if `hash(target.spec) != old_hash`, even if all output files exist.

We should allow this behaviour to be turned off via a setting, e.g. `scheduling.check_spec`.

**Comment by mailund** [comment]
In the old version, where I had python-targets, I did this hashing trick to rerun targets if the script changed. It worked reasonably well, but you want to put the hash values in a database and not a simple file per target.

**Comment by dansondergaard** [comment]
Sure, the plan was to put them all in a `targets-hashes.json` or something like that. No reason to create a file for each target :)

**Comment by mailund** [comment]
no, but I think that is how I implemented it earlier :)

**Comment by dansondergaard** [comment]
Don't tell @birc-aeh ;)

**Comment by dansondergaard** [comment]
This is done, but we need to add a setting to disable it + tests.

**Comment by dansondergaard** [comment]
Closed by 5fcb9dc89a8ea1176b4a86bd6020f641b497a02e.
