### ISSUE TITLE
Templates not working after update to 1.1?

### ISSUE THREAD

**Issue by matni18** [gwforg/gwf#193]
I have a file (gwf_templates.py) with all my template functions. For example:

```
def tabixIndex(inputfile, path='CADD'):
    options = {
        'inputs': ['{}/{}'.format(path, inputfile)],
        'outputs': ['{}/{}.tbi'.format(path, inputfile)],
        'cores': 1,
        'memory': '4g',
    }

    spec = '''
    source activate specialePy3;
    tabix -b 2 -e 2 {}/{};
    source deactivate;
    '''.format(path, inputfile)

    return options, spec
```

In my workflow I import all the templates:
`from gwf_templates import *`

I then have targets such as:

`chromosomes = list(i for i in range(1,23))
for chrom in chromosomes:
gwf.target('index_{}'.format(chrom)) << tabixIndex(inputfile='variants_chr{}.vcf.gz'.format(chrom), path='myFolder')`

This (and all my other targets made from templates) does not work after I updated to v. 1.1:

`Traceback (most recent call last):
  File "/home/matni18/miniconda3/envs/specialePy3/bin/gwf", line 11, in <module>
    sys.exit(main())
  File "/home/matni18/miniconda3/envs/specialePy3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/matni18/miniconda3/envs/specialePy3/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/matni18/miniconda3/envs/specialePy3/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/matni18/miniconda3/envs/specialePy3/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/matni18/miniconda3/envs/specialePy3/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/matni18/miniconda3/envs/specialePy3/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/matni18/miniconda3/envs/specialePy3/lib/python3.5/site-packages/gwf/plugins/status.py", line 115, in status
    graph = graph_from_config(obj)
  File "/home/matni18/miniconda3/envs/specialePy3/lib/python3.5/site-packages/gwf/core.py", line 88, in graph_from_config
    return graph_from_path(config['file'])
  File "/home/matni18/miniconda3/envs/specialePy3/lib/python3.5/site-packages/gwf/core.py", line 79, in graph_from_path
    workflow = load_workflow(basedir, filename, obj)
  File "/home/matni18/miniconda3/envs/specialePy3/lib/python3.5/site-packages/gwf/utils.py", line 68, in load_workflow
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/faststorage/home/matni18/project2/hg38/workflow.py", line 79, in <module>
    gwf.target('singletons_{}'.format(chrom)) << annotateIceland(inputfile='deCODE_2017/deCODE2017_singletons_{}.txt'.format(chrom), outputfile='deCODE_2017/annotated_hg38_chr{}_singleton_indels.txt'.format(chrom), repeatfile='Repeats/repeat_chr{}.fa.out'.format(chrom), genome='hg38.2bit')
TypeError: target() missing 2 required positional arguments: 'inputs' and 'outputs'
`

Do I need to change my code after the update?

**Comment by micknudsen** [comment]
Aren't you supposed to use [target_from_template]( http://gwf.readthedocs.io/en/latest/tutorial.html#reusable-targets-with-templates)? I thought that was mandatory already in v1.0.

**Comment by matni18** [comment]
Thanks, that worked! I have been using this workflow without problems in v1.0 so far, so it problably wasn't mandatory. I see that the `inputs` and `outputs` must also be specified outside of the `options` dict now, so I need to change all my templates :-/

**Comment by matni18** [comment]
Hmm but now it gives me this error? 
`Error: Local backend could not connect to workers on port 12345. Workers can be started by running "gwf workers". You can read more in the documentation: http://gwf.readthedocs.io/en/latest/backends.html#local`

When I try the link it just says: 
```

        \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|
           ]                     [   /  |
           ]___               ___[ ,'   |
           ]  ]\             /[  [ |:   |
           ]  ] \           / [  [ |:   |
           ]  ]  ]         [  [  [ |:   |
           ]  ]  ]__     __[  [  [ |:   |
           ]  ]  ] ]\ _ /[ [  [  [ |:   |
           ]  ]  ] ] (#) [ [  [  [ :===='
           ]  ]  ]_].nHn.[_[  [  [
           ]  ]  ]  HHHHH. [  [  [
           ]  ] /   `HH("N  \ [  [
           ]__]/     HHH  "  \[__[
           ]         NNN         [
           ]         N/"         [
           ]         N H         [
          /          N            \
         /           q,            \
        /                           \

```

I have no idea what workers are?

**Comment by micknudsen** [comment]
Workers are kind of pseudo-nodes for when you want to test your workflow on a local backend. If you want to run on Slurm, try:

`gwf config set backend slurm`

in your workflow folder.

Hey @dansondergaard: Broken link!

**Comment by micknudsen** [comment]
Fixed broken link in Pull Request #194.

**Comment by dansondergaard** [comment]
@matni18, indeed, you should return `inputs` and `outputs` separately from templates (since 1.0).

By default *gwf* will use a backend called "local" which doesn't depend on Slurm. However, it still needs something to submit targets to, so therefore the user must starts a bunch of workers (processes that can run targets). The local backend is meant for testing and running small workflows locally, so it's not as robust og feature complete as the Slurm backend.

As @micknudsen says, you should configure *gwf* to use the Slurm backend if you want to submit targets to Slurm. Using the above command will do so permanently, but you can also use the `-b` flag:

```
gwf -b slurm run
```

**Comment by dansondergaard** [comment]
Seems all questions have been answered here, so I'll close the issue :-)
