### ISSUE TITLE
gwf status -s completed shows targets that are still running

### ISSUE THREAD

**Issue by dansondergaard** [gwforg/gwf#222]

**Comment by micknudsen** [comment]
Looks like the `-s running` option is broken, too (the blank line is the output):

```
[michaelk@fe1 workflow]$ gwf status -s running

[michaelk@fe1 workflow]$ gwf status
FilterVariants_Sera_K_Tumor [CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCR.........] 153/1/0/28
```

**Comment by dansondergaard** [comment]
Well, it actually looks right, but the status bar makes it confusing. The target FilterVariants_Sera_K_Tumor isn’t running, but one of its dependencies is, so when you ask for running targets only it isn’t shown.

**Comment by micknudsen** [comment]
Doh! I have to add `--all` to get what I want. Strange default behavior. When would that ever be useful?

**Comment by dansondergaard** [comment]
The behaviour is actually pretty consistent (however, that doesn’t mean that it’s intuitive). By default, only endpoints are shown. So ‘-s running’ shows all endpoints that are running. To show any target that’s running we must deactivate the “endpoint filter” using ‘-all’.

If you’ve got a better idea for how this should work, so it’s both consistent and intuitive, please let me know :-)

**Comment by micknudsen** [comment]
I often forget to add `--all` since intuitively I would expect it to be default. I would prefer` --endpoints` to be an option instead.
