### ISSUE TITLE
Notify user if a new version has become available

### ISSUE THREAD

**Issue by dansondergaard** [gwforg/gwf#225]
Many users struggle with bugs because they're running an old version and didn't care to check if a new version had been released.

Whenever a command is run, and `check_updates` is true, contact the update server and get the most recent release version. If the version is higher than the current version, show the user a message containing:

* how to update
* the version number of the new version
* a link to the change log
* how to suppress update notices in the future

The HTTP request to the update server should have a timeout of 1 sec and the check should at most be performed once per 24 hours.

Add `check_updates` setting to suppress update notices.

**Comment by mailund** [comment]
Make sure to make a way to disable this feature, though, since gwf might be run from behind a firewall

**Comment by dansondergaard** [comment]
That's the "how to suppress update notices in the future" point ;)
