### ISSUE TITLE
Allow more than one -s option

### ISSUE THREAD

**Issue by micknudsen** [gwforg/gwf#234]
It would be very helpful, if one could provide multiple values for the `-s` option:

`gwf status -s running,shouldrun`

If one runs

`gwf status -s running -s shouldrun`

the first `-s` instance is ignored (no errors or warnings). Is that the intended behavior?

**Comment by dansondergaard** [comment]
Gwf itself doesn't deal with argument parsing (it uses `click`), so I can't say whether it's intended behaviour. However, it's a valid feature request and should be easy to implement.
