### ISSUE TITLE
Touch all output files in order

### ISSUE THREAD

**Issue by kaspermunch** [gwforg/gwf#236]
Touch all files (both existing and/or non-existing) in the order defined by the workflow.

**Comment by micknudsen** [comment]
Why is this useful? It may be obvious...

**Comment by dansondergaard** [comment]
If a workflow has been run to completion, a file was then accidentally deleted, but one doesn't want to generate the file again when running the workflow, one can now run `gwf touch` to create an empty file with the right timestamp to fool *gwf* into thinking that the target has been run.
