### ISSUE TITLE
Scheduling on slow file system

### ISSUE THREAD

**Issue by micknudsen** [gwforg/gwf#240]
Using gwf on a slow file system sometimes leads to scheduling issues. When a file is created, the time stamp may be just date and year for several seconds:

`-rw-rw-r-- 1 user group 274039 Feb 21  2019 myfile.txt`

Later it will be updated to something more precise:

`-rw-rw-r-- 1 user group 274039 Feb 21  15:45 myfile.txt`

Sometimes this causes gwf to get the scheduling wrong. The target creating the file (and all dependencies) will be listed at `shouldrun` even though they have indeed run and generated the correct output.

**Comment by birc-aeh** [comment]
The timestamp doens't get updated, it is just `ls` attempting to be clever with how it formats the time.
If you do `ls -l --time-style=long-iso` or `=full-iso` you will get a consistent timestamp (can also be controlled through environment variable as `TIME_STYLE`).

I think what happened in this case is that the clock had drifted on some of our servers, so an output file created on one machine could end up "older" than its inputs.
There is no way for gwf to handle different machines producing inconsistent timestamps.

For whatever reason CentOS hasn't set up automatic restarts for the time keeping daemon but we have added that now, lets hope this is the last time this problem pops up :)
