### ISSUE TITLE
Log improvements

### ISSUE THREAD

**Issue by micknudsen** [gwforg/gwf#245]
Since `v1.3.0` only the latest log files are kept. This is rather annoying, when one wants to rerun failed targets and compare log files.

I know the desire to keep the amount of log files as low as possible, so would it be possible/desirable with a kind of "log-storage" which would all logs in one file? The individual logs could then be exportable using `gwf logs`.

**Comment by dansondergaard** [comment]
We could make log cleaning optional, that's definitely the easiest option.

We could also archive logs and allow the user to rewind, but I guess that's not very useful since it's hard to pinpoint which run of the workflow a log belongs to.

**Comment by dansondergaard** [comment]
With the changes coming in v2.0 I think we can provide a lot more options here. Let's discuss in person what the ideal solution would be.
