### ISSUE TITLE
Better status reporting

### ISSUE THREAD

**Issue by vang42** [gwforg/gwf#246]
When one target in a pipeline of targets fail, the remaining dependant jobs are cancelled. What is best practice for finding the failing job?

**Comment by dansondergaard** [comment]
Good question. Tighter integration with Slurm would allow us to mark targets as "failed" which should make this a lot easier. I'll have a look at it.

**Comment by dansondergaard** [comment]
This becomes a lot easier when #250 is implemented, especially when combined with writing to temporary files and `mv`ing at the end of the target.

**Comment by dansondergaard** [comment]
I've decided to go another route to get better status reporting. It's more work, but makes a lot of previously impossible things possible, as well as providing better status reporting. The changes will be released in v2.0, so I'll keep this issue open until it's released.
