### ISSUE TITLE
Cancel --force

### ISSUE THREAD

**Issue by micknudsen** [gwforg/gwf#254]
There seems to be missing an `elif not targets and force` here:

https://github.com/gwforg/gwf/blob/5bc0bbdef3dcd18346570d815218b9a8090b7b0c/src/gwf/plugins/cancel.py#L36-L44

As it is now, running `gwf cancel --force` does nothing. Shouldn't it cancel all targets?

**Comment by dansondergaard** [comment]
That's true, good catch! Will fix in 1.6 :-)
