### ISSUE TITLE
Attribute error in Python 3.8

### ISSUE THREAD

**Issue by madsheilskov** [gwforg/gwf#256]
When I run a workflow in a Python 3.8 conda environment I get this AttributeError:
```
  File "/home/mhra/anaconda3/envs/subfq/lib/python3.8/site-packages/gwf/utils.py", line 46, in __enter__
    self.start = time.clock()
AttributeError: module 'time' has no attribute 'clock'
```
When I run the same workflow in a Python 3.7 conda environment it works fine.

Could this be related to [changes in 3.8](https://docs.python.org/3/whatsnew/3.8.html) ?

> The function time.clock() has been removed, after having been deprecated since Python 3.3: use time.perf_counter() or time.process_time() instead, depending on your requirements, to have well-defined behavior. (Contributed by Matthias Bussonnier in bpo-36895.)

**Comment by dansondergaard** [comment]
Yup, I haven't tested gwf on Python 3.8 yet. I guess it should say somewhere in the docs that only 3.5-3.7 is supported. However, compatibility with 3.8 is definitely on the plan for the next gwf version :-)
