### ISSUE TITLE
Behaviour on target failure

### ISSUE THREAD

**Issue by cmkobel** [gwforg/gwf#261]
Hello. I'm missing a feature that notifies the user, when something in a pipeline has failed running. I.e. sending a email with the log, or something similar.

I'm trying to figure out if gwf has a feature to handle this situation?

Maybe it is up to the backend to handle this?

Anyway, I know I can just put a `|| mail -s "fail in target {target}...` after all my commands in the spec, but that wouldn't be as neat as having a general setup to handle failures.

**Comment by dansondergaard** [comment]
I guess what you want is to use the `mail_user` and `mail_type` options that are passed on to Slurm:

```
gwf = Workflow(defaults={
    "mail_user": "your@mail.com",
    "mail_type": "FAIL",
})
```

See the docs for `--mail-type` here https://slurm.schedmd.com/sbatch.html for more details.

**Comment by cmkobel** [comment]
Thanks a lot.
