### ISSUE TITLE
Experimental feature: Parse input-output of spec automatically

### ISSUE THREAD

**Issue by cmkobel** [gwforg/gwf#366]
Hello.

I've implemented an extension of the core functionality of gwf such that it is now possible to write a target that automatically parses its inputs and outputs from its arguments.
https://github.com/cmkobel/gwf/tree/auto-IO

This example shows how the inputs and outputs can be accessed directly, with and without subscripting, within the spec.
```
target0 = gwf.target('target0_name',
    inputs = [],
    outputs = {'A': ['aa', 'bb'], 'C': 'cc'}) >> \
        """    
        echo "Hello" > {outputs[A][0]}
        echo "World" > {outputs[A][1]}
        echo "and Jupiter!" > {outputs[C]}

        """

target1 = gwf.target('target1_name',
    inputs = target0.outputs, # short for {'A': ['aa', 'bb'], 'C': 'cc'}
    outputs = ["xx", "yy"]) >> \
        """

        ls -l {inputs}  

        cat {inputs[A]} > {outputs[0]}
        cat {inputs[A]} {inputs[C]} > {outputs[1]}
        
        """

```

In order to not break backwards-compatibility with f-strings, I've opted to utilize the >> (\_\_rshift\_\_) method for specifying the target `spec`.
The implementation uses `str()`.format() to make the inputs and outputs accessible after passing the spec string to the gwf.target class. Before inputs and outputs are passed to the format()-function, they are converted to a specialized list or dict, which has a __str__-function that prints the contents in a bash-friendly manner. 
The implementation is compatible with the inputs and outputs being defined as strings, nested lists or flat dicts. It shouldn't be a problem to support nested dicts though.

**Handling of str()[0]**
If an input or output is given as a string, it makes no sense in a practical application to subscript each letter (e.g. "{inputs[0]}"). Therefore, strings are converted to a list of length 1, which can then be gracefully subscripted.

**Current limitations**
* Dicts cannot be nested (yet)
* f-strings are not supported, unless curly-braces are escaped.
* \_\_rshift\_\_ might be a confusing choice
* The `working_dir` target argument is not yet supported.

If you like my idea, i will write some unit tests and apply for a pull request.

Happy new year
Carl

**Comment by dansondergaard** [comment]
Hi Carl,

Thank you for the pull request!

Actually, *gwf* used to have a feature like this, which I removed during the 1.0 rewrite. I didn't feel that it added any significant convenience, especially now that we have f-strings, but it does add quite a bit of "magic". Also, as you have found yourself, supporting different data types and dealing with f-strings becomes messy. I don't think we have a *really good* solution to these problems yet.

That said, others have implemented similar ideas on top of *gwf*. One purpose of the rewrite was to support such "shells" on top of *gwf*. In many ways, I think of *gwf* more as a library than an application or a domain specific language and much welcome libraries that sit on top of the *gwf* core.

**Comment by cmkobel** [comment]
OK. 
Thanks for the feedback.
I will look into making a plugin instead then.
