### ISSUE TITLE
percentage of dependencies complete for targets is always 0.00%

### ISSUE THREAD

**Issue by tw1nk0i** [gwforg/gwf#399]
I am following the [tutorial](https://gwf.app/guide/tutorial/#tutorial), except that I am using slurm. Whenever I run "gwf status", the percentage of dependencies complete for each target is always 0, and the numbers in the square brackets are always 0 (i.e. [0/0/0/0]). This occurs whether or not the targets ran successfully. I am using gwf v1.8.1 installed using conda on Linux. When I downgrade to gwf v1.7.2, it works.

**Comment by dansondergaard** [comment]
Thanks for reporting this! The issue has been fixed in the latest release (1.8.3).

The output has been changed slightly since most of the reported numbers were kind of useless. Now only the percentage completion is shown.
