### ISSUE TITLE
Add "failed" to status -s

### ISSUE THREAD

**Issue by LudvigOlsen** [gwforg/gwf#404]
When running `gwf status`, I can use `-s shouldrun` (etc.) to see the targets with that label, but for `failed` this is not allowed. 

`Error: Invalid value for '-s' / '--status': 'failed' is not one of 'shouldrun', 'submitted', 'running', 'completed'.`

Would it make sense to add failed as an option?

Also, I am unsure about the functional difference between `failed` and `shouldrun`, as I've been getting `shouldrun` for failed targets in one project and `failed` in a different project. Is this difference described somewhere?

**Comment by dansondergaard** [comment]
Hi Ludvig,

> Would it make sense to add failed as an option?

Yes, that would absolutely make sense. Will add to the next release.

> Also, I am unsure about the functional difference between failed and shouldrun, as I've been getting shouldrun for failed targets in one project and failed in a different project. Is this difference described somewhere?

The `failed` status means that Slurm returned a failed status for the last run of the target/job (so it exited with a non-zero return code). The `shouldrun` status means that the target is incomplete or not up-to-date, i.e., it's missing outputs files or an input file of the target has been updated. This can happen even though the target run didn't fail (e.g. you forgot to generate one of the files in the list of outputs).

I will add a description to the docs.

**Comment by LudvigOlsen** [comment]
Great! Thanks :)

Without having an example by hand, I feel like I've experienced failed jobs getting the `shouldrun` label. This might have been for targets already run previously though, not sure. But does `shouldrun` take priority if say, running a `shouldrun` target fails?

**Comment by dansondergaard** [comment]
> But does shouldrun take priority if say, running a shouldrun target fails?

No, if you run a `shouldrun` target and it fails it should say `failed`, but only if the job actually failed (exited with a non-zero return code). If you experience it again, check the status of the job with `jobinfo` or similar. It's definitely a bug if it doesn't behave as described above :-)

**Comment by LudvigOlsen** [comment]
Good to know. I'll keep an eye out for it! :-)
