### ISSUE TITLE
Failed targets are not recognized as failed

### ISSUE THREAD

**Issue by LudvigOlsen** [gwforg/gwf#407]
I have a job that failed but the summary says `failed 0`.

The target did not produce the expected output files before failing. If I call `gwf run` again, the job is submitted again.

![billede](https://github.com/gwforg/gwf/assets/22819047/fafefa33-128d-486e-9729-cc3ef0406681)

![billede](https://github.com/gwforg/gwf/assets/22819047/1de1372f-1357-4ccc-9ea4-5a3b13b80f66)

![billede](https://github.com/gwforg/gwf/assets/22819047/f476fa3b-92a9-457b-812b-a4d22f5b0c8d)

![Skærmbillede 2023-10-18 kl  20 03 49](https://github.com/gwforg/gwf/assets/22819047/33fa8c46-0173-4ffc-9533-fcc5c3123aea)

I have since fixed the error in the code so probably can't reproduce. But seems there might be a bug in gwf?

I'm running `version 2.0.4`.

**Comment by dansondergaard** [comment]
As far as I remember, if a target fails and doesn't produce the intended output files, it will be reported as "shouldrun". If it fails, but produced the files anyway, gwf will report it as "failed". It may not be a useful distinction, but in general thinks of target with missing/outdated output files as "shouldrun".

**Comment by dansondergaard** [comment]
I haven't heard about this from anybody else, so it could be a very, very rare timing issue or something related to how Slurm reports states. Closing for now.
