### ISSUE TITLE
Workflow arguments

### ISSUE THREAD

**Issue by ymer** [gwforg/gwf#94]
It would be nice if workflows could be called with custom arguments.

**Comment by mailund** [comment]
We are working on it :)

**Comment by dansondergaard** [comment]
As a short-term fix, one could use environment variables:

```
import os
DATA_FILE = os.getenv('DATA_FILE', 'big_data_file.txt')
```

This will look for the environment variable `DATA_FILE`. If it's not present, the default `big_data_file.txt` will be used. If you want to use another data file, you can do this:

```
$ DATA_FILE=small_data_file.txt gwf
```

I'm not sure how workflow argument should work at the moment. I actually like just using environment variables.

**Comment by mailund** [comment]
Environment variables and options are Very Bad if they affect how the workflow runs. You are putting the workflow logic outside of the workflow. I think adding options to extend gwf is a good idea but I don't much like adding functionality that is easily abused to affect the actual workflow. @ymer do you have a use case you can show of how you want to use it?

**Comment by dansondergaard** [comment]
How are they bad? There is no logic outside the workflow, only "configuration". I think it's pretty useful to be able to run a workflow on a test data file without changing the workflow targets at all.

**Comment by mailund** [comment]
It certainly depends on what you do with it. There is nothing wrong with being able to run the workflow on test data. But anything that isn't explicitly written in the workflow is essentially undocumented, so it is something to be careful about at least.

**Comment by dansondergaard** [comment]
That's true. We will be relying on the author of the workflow to clearly document all of the workflow arguments.

**Comment by dansondergaard** [comment]
After some off-GitHub correspondence with @ymer I've decided to re-focus this issue. However, I think that we should document at least one approach for passing "configuration" to workflows. One approach, the one used by @ymer, is basically to have a `run.py` script that takes the necessary arguments and pickles them to disk. It then runs the workflow, which reads the pickled config.
